// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1jM71Dh6x714pKlRtAntBzc5itjm_kM',
    appId: '1:45250695471:web:8dcc421785a6c5a11511da',
    messagingSenderId: '45250695471',
    projectId: 'habit-20bf4',
    authDomain: 'habit-20bf4.firebaseapp.com',
    storageBucket: 'habit-20bf4.firebasestorage.app',
    measurementId: 'G-D8RXY8L8XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ecU1NvBm4x6sYPIDP_IrF_VJATaOCBU',
    appId: '1:45250695471:android:fb32c4c82844c0b81511da',
    messagingSenderId: '45250695471',
    projectId: 'habit-20bf4',
    storageBucket: 'habit-20bf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiV3Axjy9hzkuPKw3K8FomjCB2ZZ_nhqQ',
    appId: '1:45250695471:ios:9dd78e5c88d1c5871511da',
    messagingSenderId: '45250695471',
    projectId: 'habit-20bf4',
    storageBucket: 'habit-20bf4.firebasestorage.app',
    iosBundleId: 'com.habit.habit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiV3Axjy9hzkuPKw3K8FomjCB2ZZ_nhqQ',
    appId: '1:45250695471:ios:c3fd7070149705e21511da',
    messagingSenderId: '45250695471',
    projectId: 'habit-20bf4',
    storageBucket: 'habit-20bf4.firebasestorage.app',
    iosBundleId: 'com.example.habit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf1jM71Dh6x714pKlRtAntBzc5itjm_kM',
    appId: '1:45250695471:web:71800f08fcaf6f911511da',
    messagingSenderId: '45250695471',
    projectId: 'habit-20bf4',
    authDomain: 'habit-20bf4.firebaseapp.com',
    storageBucket: 'habit-20bf4.firebasestorage.app',
    measurementId: 'G-L5QWZ9SZKC',
  );
}
